grid_map_topic: /local_environment/grid_map
grid_map_visualizations:
  - name: ground
    type: point_cloud
    params:
      layer: ground_height
  - name: height_range
    type: occupancy_grid
    params:
      layer: height_range
      data_min: 0.0
      data_max: 1.5
  - name: observed
    type: occupancy_grid
    params:
      layer: observed_mask
      data_min: 0.0
      data_max: 1.0
